alias ..='cd ..'
alias a='ls -a'
alias c='cat'
alias v='vim'
alias m='mc'
alias arm='make ARCH=arm -j4'
alias rearm='make ARCH=arm clean ; make ARCH=arm -j4'
alias oboot='usbboot -f'
alias ram_unpack='gunzip -c ../ramdisk.img | cpio -i'
alias ram_pack='find . | cpio -o -H newc | gzip > ../ramdisk.img'
alias show='git show'
alias blame='git blame'
alias br='git branch -a'
alias checkout='git checkout'
alias one='git log --oneline'
alias log='git log'
alias am='git am'
alias amend='git commit --amend'
alias format='git format-patch -1'
alias add='git add'
alias rebase='git svn rebase'
alias grebase='repo forall -c "git pull --rebase"'
alias abort='git am --abort'
alias stash='git stash'
alias pop='git stash pop'
alias gdiff='git diff'
alias addu='git add -u'
alias tag='git tag'
alias clone='git svn clone'
alias externals='URL=`git svn info | grep URL | cut -d " " -f2` ; svn propget svn:externals $URL'
alias lg="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias lgr="git log --color --reverse --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gsend='git send-email --smtp-server /usr/bin/msmtp --from "${USER_REAL_NAME} <${TI_MAIL}>" --envelope-sender="${USER_REAL_NAME} <${TI_MAIL}>" --suppress-cc=all'
alias gsendcompose='git send-email --smtp-server /usr/bin/msmtp --from "${USER_REAL_NAME} <${TI_MAIL}>" --envelope-sender="${USER_REAL_NAME} <${TI_MAIL}>" --suppress-cc=all --compose'
alias cpio_pack='find . | cpio -o -H newc > ../newramdisk.cpio'
alias cpio_unpack='cat ../ramdisk.cpio | cpio -i'
alias swapon='sudo swapon -a'
alias swapoff='sudo swapoff -a'
alias clean_yocto_fs_6.1.5='rm -rf /opt/intel/puma6-r6.1.5-ga/puma6-build-thirdpartywifi/thirdpartywifi_r6.1.5-ga/build-intelce/tmp/work/core2-32-poky-linux/uimage/1.0-r0/targetFS_gateway'
alias rm_rf='f(){ mkdir empty_dir; rsync -a --delete empty_dir/ "$1" ; rm -rf empty_dir; rm -rf "$1" ; unset -f f; }; f'
